import type { Metadata } from 'next'
import '@/assets/styles/globals.scss'
import ApiProvider from '@/features/api-provider/ApiProvider'
import Header from '@/widgets/header/Header'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
	title: 'Todo - Напоминание',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className='dark max-w-screen-2xl m-auto'>
				<ApiProvider>
					<Header />
					<main>{children}</main>
					<ToastContainer theme='dark' position='bottom-right' />
				</ApiProvider>
			</body>
		</html>
	)
}
