import type { Metadata } from 'next'
import './globals.scss'
import ApiProvider from '@/features/api-provider/ApiProvider'

export const metadata: Metadata = {
	title: 'Todo - Напоминание',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className='dark'>
				<ApiProvider>{children}</ApiProvider>
			</body>
		</html>
	)
}
